name: Deploy

on:
  push:
    branches:
      - main

defaults:
    run:
        shell: bash

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - uses: crazy-max/ghaction-github-runtime@v3
            - uses: actions/setup-node@v4
              with:
                node-version: '16.20.1'
            - name: Sentry
              run: npm config set unsafe-perm true
              shell: bash
            - name: Install dependencies
              run: npm install
            - name: Generate
              run: npm run generate